#!/usr/bin/env python3
"""
Aggregate per-slice results into a single SUMMARY.md.

Inputs:
- <reports_dir>/results.json (generated by run_claude_slices.py)
Outputs:
- <reports_dir>/SUMMARY.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def _read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Aggregate slice reports into SUMMARY.md")
    ap.add_argument("--reports-dir", required=True, help="Path to one run directory (contains results.json)")
    args = ap.parse_args(argv)

    reports_dir = Path(args.reports_dir)
    results_path = reports_dir / "results.json"
    run_path = reports_dir / "run.json"

    if not results_path.exists():
        raise SystemExit(f"Missing results.json: {results_path}")

    results = _read_json(results_path)
    run_meta = _read_json(run_path) if run_path.exists() else {}

    lines: list[str] = []
    lines.append("# Docs ↔ Code Audit Summary")
    lines.append("")
    if run_meta:
        lines.append("## Run metadata")
        lines.append("")
        for k in ("code_repo_root", "docs_repo_root", "docs_repo_ref", "product_version", "started_at"):
            if k in run_meta:
                lines.append(f"- **{k}**: `{run_meta[k]}`")
        lines.append("")

    ok_cnt = sum(1 for r in results if r.get("ok"))
    lines.append(f"## Results (ok={ok_cnt} failed={len(results)-ok_cnt})")
    lines.append("")
    lines.append("| Slice | Status | Report | Duration (ms) |")
    lines.append("|---|---:|---|---:|")
    for r in results:
        sid = r.get("slice_id", "?")
        ok = bool(r.get("ok"))
        status = "OK" if ok else "FAIL"
        report_rel = f"{sid}/slice_report.md"
        duration = r.get("duration_ms", "")
        lines.append(f"| `{sid}` | **{status}** | `{report_rel}` | {duration} |")

    (reports_dir / "SUMMARY.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main([]))


